spring:
  application:
    name: game_detector
  data:
    jdbc:
      dialect: mysql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306
  jpa:
    hibernate:
      ddl-auto: update
  quartz:
    auto-startup: false